# Render.com configuration for Chillers POS
services:
  - type: web
    name: pos
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
    autoDeploy: true

databases:
  - name: pos-database
    databaseName: pos_db
    user: pos_user
